### ISSUE TITLE
when the number of files exceeds 3170, the LIST command crashes

### ISSUE THREAD

**Issue by rianwouters** [sstur/nodeftpd#101]
when the number of files exceeds 3170, the LIST command generates the following exception:

FTP command: LIST
Directory has 3170 files
/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:677
return x.localeCompare(y);
 ^
RangeError: Maximum call stack size exceeded
at String.localeCompare (native)
at sf (/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:677:24)
at /home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:681:20
at Array.sort (native)
at finished (/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:679:31)
at handleFile (/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:643:40)
at /home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:658:11
at FtpServer.self.getGroupFromGid (/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:99:5)
at /home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:646:21
at FtpServer.self.getUsernameFromUid (/home/sesame/lumipark/node_modules/ftpd/lib/ftpd.js:96:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by rianwouters** [comment]
it's caused by the recursive handleFile function in combination with the synchronous getUserName and getGroup.

**Comment by sstur** [comment]
Hi. Thanks for reporting this issue. Sorry for the delay (I need more maintainers for this project). I'll take a look at your PR now.

**Comment by rianwouters** [comment]
You may want to check my fork

Verzonden van mijn HTC

----- Reply message -----
Van: "Simon Sturmer" <notifications@github.com>
Aan: "sstur/nodeftpd" <nodeftpd@noreply.github.com>
CC: "rianwouters" <rianwouters@hotmail.com>, "Author" <author@noreply.github.com>
Onderwerp: [sstur/nodeftpd] when the number of files exceeds 3170, the LIST command crashes (#101)
Datum: wo, jun. 15, 2016 14:39


Hi. Thanks for reporting this issue. Sorry for the delay (I need more maintainers for this project). I'll take a look at your PR now.

---
