### ISSUE TITLE
Runtime error after migration to Node 7

### ISSUE THREAD

**Issue by Shden** [sstur/nodeftpd#119]
This occurred after upgrade to Node 7:

```
util.js:965
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:965:11)
    at Object.<anonymous> (/Users/den/ShHarbor/videoMonitoring/NVRConnector/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ({require directive in my code})
```

The code used to work before node upgrade.

**Comment by Systerr** [comment]
that because of 
```util.inherits(FtpConnection, process.EventEmitter);```
On node v6 it was deprecated, on node v7 was it removed 
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#process
https://github.com/nodejs/node/wiki/Breaking-changes-between-v6-and-v7#process

**Comment by Systerr** [comment]
Hmmm. Project codebase have no that code, but npm package have
Please look to another issue #115

**Comment by Shden** [comment]
Thanks.

Any plans to have it fixed somewhere? BTW, for some reason github version works fine, seems this is because it is different from nom package version.

Thank you.

Kind regards,

---
Dennis Afanassiev
DataArt
+7-921-931-6709

19 дек. 2016 г., в 16:20, Andrey <notifications@github.com<mailto:notifications@github.com>> написал(а):


that because of
util.inherits(FtpConnection, process.EventEmitter);
On node v6 it was deprecated, on node v7 was it removed
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#process
https://github.com/nodejs/node/wiki/Breaking-changes-between-v6-and-v7#process

**Comment by wayofthefuture** [comment]
Any word on this? FTPD completely broken on Node V7.7...

**Comment by Systerr** [comment]
@wayofthefuture  please look at #115 and use github version
