### ISSUE TITLE
Error when using TLS

### ISSUE THREAD

**Issue by waltergms** [sstur/nodeftpd#127]
<::ffff:177.206.84.50> << LIST
<::ffff:177.206.84.50> FTP command: LIST
<::ffff:177.206.84.50> Directory has 3 files
<::ffff:177.206.84.50> >> 150 Here comes the directory listing
<::ffff:177.206.84.50> Sending file list
<::ffff:177.206.84.50> >> -rw-r--r-- 1 ftp ftp          480 Jan 31 15:01 doc1.txt
<::ffff:177.206.84.50> >> -rw-r--r-- 1 ftp ftp          725 Jan 31 13:51 doc2.txt
<::ffff:177.206.84.50> >> drwxr-xr-x 1 ftp ftp         4096 Jan 31 13:52 Nova pasta
<::ffff:177.206.84.50> >> 226 Transfer OK
ERROR: <::ffff:177.206.84.50> Data connection error: { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Trace: Trace follows
    at FtpServer._logIf (/wanas03/shared_config/ftpNodejs/node_modules/ftpd/lib/FtpServer.js:141:13)
    at FtpConnection._logIf (/wanas03/shared_config/ftpNodejs/node_modules/ftpd/lib/FtpConnection.js:43:22)
    at Socket.<anonymous> (/wanas03/shared_config/ftpNodejs/node_modules/ftpd/lib/FtpConnection.js:200:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

When i connect using simple FTP (unsecure) it connects and list files OK, but when i use the option use TLS if possible the connection goes ok but i do not receive the file list and got the error above.

**Comment by waltergms** [comment]
Answer:	220 FTP server (nodeftpd) ready
Command:	AUTH TLS
Answer:	234 Honored
State:	A iniciar o TLS...
Erro:	GnuTLS erro -110: The TLS connection was non-properly terminated.

**Comment by davidAtBar** [comment]
Happens to me as well:

info: client connected: undefined
19|ftpserv | Connection
19|ftpserv | FTP command: AUTH TLS
19|ftpserv | Establishing secure connection...
19|ftpserv | Secure socket not authorized: { Error: unable to get issuer certificate
19|ftpserv |     at Error (native)
19|ftpserv |     at SecurePair.<anonymous> (*/node_modules/ftpd/lib/starttls.js:61:47)
19|ftpserv |     at emitNone (events.js:86:13)
19|ftpserv |     at SecurePair.emit (events.js:185:7)
19|ftpserv |     at SecurePair.maybeInitFinished (_tls_legacy.js:819:10)
19|ftpserv |     at CleartextStream._read (_tls_legacy.js:274:13)
19|ftpserv |     at CleartextStream.Readable.read (_stream_readable.js:348:10)
19|ftpserv |     at EncryptedStream._write (_tls_legacy.js:171:25)
19|ftpserv |     at doWrite (_stream_writable.js:334:12)
19|ftpserv |     at writeOrBuffer (_stream_writable.js:320:5) code: 'UNABLE_TO_GET_ISSUER_CERT' }
19|ftpserv | Closing unauthorized connection (allowUnauthorizedTls==false)
19|ftpserv | Client connection ended
19|ftpserv | Client connection closed
19|ftpserv | info: client connected: undefined
19|ftpserv | Connection
19|ftpserv | FTP command: AUTH TLS
19|ftpserv | Establishing secure connection...
19|ftpserv | Secure socket not authorized: { Error: unable to get issuer certificate
19|ftpserv |     at Error (native)
19|ftpserv |     at SecurePair.<anonymous> (*/node_modules/ftpd/lib/starttls.js:61:47)
19|ftpserv |     at emitNone (events.js:86:13)
19|ftpserv |     at SecurePair.emit (events.js:185:7)
19|ftpserv |     at SecurePair.maybeInitFinished (_tls_legacy.js:819:10)
19|ftpserv |     at CleartextStream._read (_tls_legacy.js:274:13)
19|ftpserv |     at CleartextStream.Readable.read (_stream_readable.js:348:10)
19|ftpserv |     at EncryptedStream._write (_tls_legacy.js:171:25)
19|ftpserv |     at doWrite (_stream_writable.js:334:12)
19|ftpserv |     at writeOrBuffer (_stream_writable.js:320:5) code: 'UNABLE_TO_GET_ISSUER_CERT' }
19|ftpserv | Closing unauthorized connection (allowUnauthorizedTls==false)
19|ftpserv | Client connection ended
19|ftpserv | Client connection closed

**Comment by felipe-pereira** [comment]
@davidAtBar you error is in the CA_FILES (probably a bad path or wrong format), that's not the same error @waltergms has (in this case the client is closing the connection).

Filezilla claims that any server with [this vulnerability](https://forum.filezilla-project.org/viewtopic.php?f=2&t=7688) will yield a "_GnuTLS erro -110: The TLS connection was non-properly terminated._", does someone knows if nodeftpd has that vulnerability?

Thanks
