### ISSUE TITLE
550 Could not get file size.

### ISSUE THREAD

**Issue by Bocha91** [sstur/nodeftpd#59]
normally works so:

SIZE /mdem1.txt
550 Could not get file size.

this version falls:

FTP command: SIZE /mdem1.txt
Error getting size of file '\mdem1.txt'
Trace: Trace follows
    at FtpServer._logIf (E:\PCAD\ECG_GSM\SOFT\PC\nw.server\node_modules\ftpd\lib\ftpd.js:183:15)
    at FtpServer._traceIf E:\PCAD\ECG_GSM\SOFT\PC\nw.server\node_modules\ftpd\lib\ftpd.js:188:15)
    at FtpConnection._traceIf (E:\PCAD\ECG_GSM\SOFT\PC\nw.server\node_modules\ftpd\lib\ftpd.js:208:22)
    at E:\PCAD\ECG_GSM\SOFT\PC\nw.server\node_modules\ftpd\lib\ftpd.js:1220:12
    at Object.oncomplete (fs.js:107:15)

correct please.

**Comment by Bocha91** [comment]
ftpd.js line 1214 - 1216 change :

FtpConnection.prototype._command_SIZE = function(commandArg) {
  var self = this;

  var filename = withCwd(self.cwd, commandArg);
  self.fs.stat(pathModule.join(self.root, filename), function(err, s) {
    if (err) {
<b>/*     self._traceIf(0, "Error getting size of file '" + filename + "' ", self.socket); */
      self.respond("550 Could not get file size.");</b>
      return;
    }
    self.respond("213 " + s.size + "");
  });
};


good !
